/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author micheacolautti
 */
public class ImagesFrame extends javax.swing.JFrame {

    /**
     * Creates new form ImagesFrame
     */
    public ImagesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empty2 = new Altitudine();
        imagePanelFront1 = new ImagePanelFront();
        imagePanelLat1 = new ImagePanelLat();
        imagePanelUp1 = new ImagePanelUp();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 2));
        getContentPane().add(empty2);

        javax.swing.GroupLayout imagePanelFront1Layout = new javax.swing.GroupLayout(imagePanelFront1);
        imagePanelFront1.setLayout(imagePanelFront1Layout);
        imagePanelFront1Layout.setHorizontalGroup(
            imagePanelFront1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );
        imagePanelFront1Layout.setVerticalGroup(
            imagePanelFront1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        getContentPane().add(imagePanelFront1);

        javax.swing.GroupLayout imagePanelLat1Layout = new javax.swing.GroupLayout(imagePanelLat1);
        imagePanelLat1.setLayout(imagePanelLat1Layout);
        imagePanelLat1Layout.setHorizontalGroup(
            imagePanelLat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );
        imagePanelLat1Layout.setVerticalGroup(
            imagePanelLat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        getContentPane().add(imagePanelLat1);

        javax.swing.GroupLayout imagePanelUp1Layout = new javax.swing.GroupLayout(imagePanelUp1);
        imagePanelUp1.setLayout(imagePanelUp1Layout);
        imagePanelUp1Layout.setHorizontalGroup(
            imagePanelUp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );
        imagePanelUp1Layout.setVerticalGroup(
            imagePanelUp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        getContentPane().add(imagePanelUp1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImagesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImagesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImagesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImagesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImagesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Altitudine empty2;
    private ImagePanelFront imagePanelFront1;
    private ImagePanelLat imagePanelLat1;
    private ImagePanelUp imagePanelUp1;
    // End of variables declaration//GEN-END:variables
}
