package DronePk;

import ImageFrame.ImageFrame;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Panel che si occupa dei bottoni.
 *
 * @author Alessandro Aloise
 * @version 28.01.2021
 */
public class FunzionePanel extends javax.swing.JPanel {

    /**
     * Istanziamento dell'oggetto drone.
     */
    private Drone drone;
    
    private LeapMotionProject lm;

    /**
     * Creates new form FunzionePanel
     */
    public FunzionePanel() {
        initComponents();
        try {
            drone = new Drone(this);
        } catch (IOException ex) {
            Logger.getLogger(FunzionePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        drone.start();
        drone.command();
        batteria();
    }
    
    public void setLM(LeapMotionProject lm) {
        this.lm = lm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sequenzaTasti = new javax.swing.JButton();
        seqName = new javax.swing.JTextField();
        Statistiche = new javax.swing.JButton();
        vistaDrone = new javax.swing.JButton();
        decolla = new javax.swing.JButton();
        atterra = new javax.swing.JButton();
        batteriaText = new javax.swing.JLabel();
        batteriaL = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        sequenzaTasti.setText("ESEGUI SEQUENZA");
        sequenzaTasti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sequenzaTastiActionPerformed(evt);
            }
        });
        add(sequenzaTasti);

        seqName.setText("EXAMPLE");
        add(seqName);

        Statistiche.setText("STATISTICHE");
        add(Statistiche);

        vistaDrone.setText("VISTA DRONE");
        vistaDrone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vistaDroneActionPerformed(evt);
            }
        });
        add(vistaDrone);

        decolla.setText("DECOLLA");
        decolla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decollaActionPerformed(evt);
            }
        });
        add(decolla);

        atterra.setText("ATTERA");
        atterra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atterraActionPerformed(evt);
            }
        });
        add(atterra);

        batteriaText.setText("Batteria");
        add(batteriaText);

        batteriaL.setText("                  ");
        add(batteriaL);
    }// </editor-fold>//GEN-END:initComponents

    private void vistaDroneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vistaDroneActionPerformed
        ImageFrame vista = new ImageFrame();
        vista.setVisible(true);
    }//GEN-LAST:event_vistaDroneActionPerformed

    private void decollaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decollaActionPerformed
        drone.decolla();
    }//GEN-LAST:event_decollaActionPerformed

    private void atterraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atterraActionPerformed
        drone.atterra();
    }//GEN-LAST:event_atterraActionPerformed

    private void sequenzaTastiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sequenzaTastiActionPerformed
        lm.runSequence();
    }//GEN-LAST:event_sequenzaTastiActionPerformed

    /**
     * Ritorna il nome della sequenza del textbox.
     */
    public String getSeqName() {
        return seqName.getText();
    }
    
    
    public void batteria(){
        try {
            sleep(1000);
            batteriaL.setText(drone.batteria() + "%   ");
        } catch (InterruptedException ex) {
            Logger.getLogger(FunzionePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Statistiche;
    private javax.swing.JButton atterra;
    private javax.swing.JLabel batteriaL;
    private javax.swing.JLabel batteriaText;
    private javax.swing.JButton decolla;
    private javax.swing.JTextField seqName;
    private javax.swing.JButton sequenzaTasti;
    private javax.swing.JButton vistaDrone;
    // End of variables declaration//GEN-END:variables
}
